module.exports = {
    create_new_room_page_title:                             "Create New Room",
    front_page_title:                                       "Front Page",
    private_chat_page_title:                                "Private Chat Page",
    public_chat_page_title:                                 "Public Chat Page",
    navbar_create_room:                                     "Create Room",
    navbar_login:                                           "Login",
    navbar_logout:                                          "Logout",
    navbar_active_rooms:                                    "Active Rooms",
    navbar_all_rooms:                                       "All Rooms",
    navbar_total_users_online:                              "Total Users Online:",
    frontpage_corner_joinroom_button:                       "Join Room",
    frontpage_is_on_mic:                                    "is on mic",
    frontpage_room_:                                        "Room-",
    frontpage_online:                                       "Online",
    frontpage_login_or_register:                            "Login Or Register",
    frontpage_click_here_to_register:                       "Click here to Register",
    frontpage_username:                                     "USERNAME",
    frontpage_password:                                     "PASSWORD",
    frontpage_guest_login:                                  "GUEST LOGIN",
    frontpage_remember_me:                                  "REMEMBER ME",
    frontpage_auto_login_next_visit:                        "AUTO LOGIN NEXT VISIT",
    frontpage_login:                                        "Login",
    frontpage_forgot_password:                              "FORGOT PASSWORD",
    frontpage_terms_and_conditions:                         "TERMS AND CONDITIONS",
    frontpage_email:                                        "EMAIL",
    frontpage_upload_picture:                               "UPLOAD PICTRUE",
    frontpage_register:                                     "Register",
    frontpage_room_password:                                "ROOM PASSWORD",
    frontpage_email_address_or_username:                    "EMAIL ADDRESS OR USERNAME",
    frontpage_retrieve_password:                            "RETRIVE PASSWORD",
    frontpage_verify_code:                                  "VERIFY CODE",
    frontpage_verify:                                       "Verify",
    frontpage_resend_verify_code:                           "RESEND VERIFY CODE",
    frontpage_error:                                        "Error",
    frontpage_success:                                      "Success",
    frontpage_internal_server_error:                        "Internal server error.",
    cnrpage_room_name:                                      "ROOM NAME",
    cnrpage_room_details:                                   "ROOM DETAILS",
    cnrpage_room_capacity:                                  "ROOM CAPACITY",
    cnrpage_upload_picture:                                 "UPLOAD PICTRUE",
    cnrpage_room_options:                                   "ROOM OPTIONS",
    cnrpage_users_cannot_use_mic:                           "users cannot use mic",
    cnrpage_users_cannot_use_cam:                           "users cannot use cam",
    cnrpage_users_cannot_text:                              "users cannot text",
    cnrpage_room_password:                                  "ROOM PASSWORD",
    cnrpage_room_note:                                      "Note: Room will be deactivated if there are no users after 3 hours or hours set inactive by admin.",
    cnrpage_create_room:                                    "CREATE ROOM",
    cnrpage_error:                                          "Error",
    cnrpage_success:                                        "Success",
    publicpage_profile:                                     "PROFILE",
    publicpage_username:                                    "USERNAME",
    publicpage_password:                                    "PASSWORD",
    publicpage_email:                                       "EMAIL",
    publicpage_upload_picture:                              "UPLOAD PICTRUE",
    publicpage_update:                                      "Update",
    publicpage_moderator_command:                           "Moderator Command",
    publicpage_warning:                                     "Warnning",
    publicpage_error:                                       "Error",
    publicpage_incoming_request:                            "Incoming request",
    publicpage_user_want_private_chat:                      "A user wants to have private chat with you.",
    publicpage_accept:                                      "Accept",
    publicpage_reject:                                      "Reject",
    publicpage_success:                                     "Success",
    publicpage_send:                                        "Send",
    publicpage_cant_call_by_yourself:                       "Can't have private chat by yourself",
    plz_go_back_to_public_page_to_start_new_private_chat:   "Please go back to public page to start new private chat.",
    privatepage_you_started_private_chat_with:              "You have started private chat with",
    privatepage_send:                                       "Send",
    privatepage_opponent_goes_offline:                      "opponent goes offline...",
    privatepage_error:                                      "Error",
    privatepage_warning:                                    "Warning",
    privatepage_not_allowed_text:                           "You are note allowed for text chat...",
    server_moderator_disallowed_text:                       "Moderator disallowed you for using Text.",
    server_user_text_disabled_success:                      "User text disabled successfully.",
    server_moderator_allowed_text:                          "Moderator allowed you for using Text.",
    server_user_text_enabled_success:                       "User text enabled successfully.",
    server_moderator_disallowed_mic:                        "Moderator disallowed you for using Mic.",
    server_user_mic_disabled_success:                       "User mic disabled successfully.",
    server_moderator_allowed_camera:                        "Moderator allowed you for using Camera.",
    server_moderator_disallowed_camera:                     "Moderator disallowed you for using Camera.",
    server_user_camera_disabled_success:                    "User camera disabled successfully.",
    server_moderator_allowed_mic:                           "Moderator allowed you for using Mic.",
    server_sorry_your_call_rejected:                        "Sorry, your call is rejected.",
    server_you_were_kicked:                                 "You were kicked.",
    server_you_were_banned:                                 "You were banned.",
    server_user_banned_success:                             "User banned successfully.",
    server_user_unbanned_success:                           "User unbanned successfully.",
    

};
